require 'bindata'

class FibRgFcLcb97 < BinData::Record
  endian :little

  uint32 :fcStshfOrig
  uint32 :lcbStshfOrig
  uint32 :fcStshf
  uint32 :lcbStshf
  uint32 :fcPlcffndRef
  uint32 :lcbPlcffndRef
  uint32 :fcPlcffndTxt
  uint32 :lcbPlcffndTxt
  uint32 :fcPlcfandRef
  uint32 :lcbPlcfandRef
  uint32 :fcPlcfandTxt
  uint32 :lcbPlcfandTxt
  uint32 :fcPlcfSed
  uint32 :lcbPlcfSed
  uint32 :fcPlcPad
  uint32 :lcbPlcPad
  uint32 :fcPlcfPhe
  uint32 :lcbPlcfPhe
  uint32 :fcSttbfGlsy
  uint32 :lcbSttbfGlsy
  uint32 :fcPlcfGlsy
  uint32 :lcbPlcfGlsy
  uint32 :fcPlcfHdd
  uint32 :lcbPlcfHdd
  uint32 :fcPlcfBteChpx
  uint32 :lcbPlcfBteChpx
  uint32 :fcPlcfBtePapx
  uint32 :lcbPlcfBtePapx
  uint32 :fcPlcfSea
  uint32 :lcbPlcfSea
  uint32 :fcSttbfFfn
  uint32 :lcbSttbfFfn
  uint32 :fcPlcfFldMom
  uint32 :lcbPlcfFldMom
  uint32 :fcPlcfFldHdr
  uint32 :lcbPlcfFldHdr
  uint32 :fcPlcfFldFtn
  uint32 :lcbPlcfFldFtn
  uint32 :fcPlcfFldAtn
  uint32 :lcbPlcfFldAtn
  uint32 :fcPlcfFldMcr
  uint32 :lcbPlcfFldMcr
  uint32 :fcSttbfBkmk
  uint32 :lcbSttbfBkmk
  uint32 :fcPlcfBkf
  uint32 :lcbPlcfBkf
  uint32 :fcPlcfBkl
  uint32 :lcbPlcfBkl
  uint32 :fcCmds
  uint32 :lcbCmds
  uint32 :fcUnused1
  uint32 :lcbUnused1
  uint32 :fcSttbfMcr
  uint32 :lcbSttbfMcr
  uint32 :fcPrDrvr
  uint32 :lcbPrDrvr
  uint32 :fcPrEnvPort
  uint32 :lcbPrEnvPort
  uint32 :fcPrEnvLand
  uint32 :lcbPrEnvLand
  uint32 :fcWss
  uint32 :lcbWss
  uint32 :fcDop
  uint32 :lcbDop
  uint32 :fcSttbfAssoc
  uint32 :lcbSttbfAssoc
  uint32 :fcClx
  uint32 :lcbClx
  uint32 :fcPlcfPgdFtn
  uint32 :lcbPlcfPgdFtn
  uint32 :fcAutosaveSource
  uint32 :lcbAutosaveSource
  uint32 :fcGrpXstAtnOwners
  uint32 :lcbGrpXstAtnOwners
  uint32 :fcSttbfAtnBkmk
  uint32 :lcbSttbfAtnBkmk
  uint32 :fcUnused2
  uint32 :lcbUnused2
  uint32 :fcUnused3
  uint32 :lcbUnused3
  uint32 :fcPlcSpaMom
  uint32 :lcbPlcSpaMom
  uint32 :fcPlcSpaHdr
  uint32 :lcbPlcSpaHdr
  uint32 :fcPlcfAtnBkf
  uint32 :lcbPlcfAtnBkf
  uint32 :fcPlcfAtnBkl
  uint32 :lcbPlcfAtnBkl
  uint32 :fcPms
  uint32 :lcbPms
  uint32 :fcFormFldSttbs
  uint32 :lcbFormFldSttbs
  uint32 :fcPlcfendRef
  uint32 :lcbPlcfendRef
  uint32 :fcPlcfendTxt
  uint32 :lcbPlcfendTxt
  uint32 :fcPlcfFldEdn
  uint32 :lcbPlcfFldEdn
  uint32 :fcUnused4
  uint32 :lcbUnused4
  uint32 :fcDggInfo
  uint32 :lcbDggInfo
  uint32 :fcSttbfRMark
  uint32 :lcbSttbfRMark
  uint32 :fcSttbfCaption
  uint32 :lcbSttbfCaption
  uint32 :fcSttbfAutoCaption
  uint32 :lcbSttbfAutoCaption
  uint32 :fcPlcfWkb
  uint32 :lcbPlcfWkb
  uint32 :fcPlcfSpl
  uint32 :lcbPlcfSpl
  uint32 :fcPlcftxbxTxt
  uint32 :lcbPlcftxbxTxt
  uint32 :fcPlcfFldTxbx
  uint32 :lcbPlcfFldTxbx
  uint32 :fcPlcfHdrtxbxTxt
  uint32 :lcbPlcfHdrtxbxTxt
  uint32 :fcPlcffldHdrTxbx
  uint32 :lcbPlcffldHdrTxbx
  uint32 :fcStwUser
  uint32 :lcbStwUser
  uint32 :fcSttbTtmbd
  uint32 :lcbSttbTtmbd
  uint32 :fcCookieData
  uint32 :lcbCookieData
  uint32 :fcPgdMotherOldOld
  uint32 :lcbPgdMotherOldOld
  uint32 :fcBkdMotherOldOld
  uint32 :lcbBkdMotherOldOld
  uint32 :fcPgdFtnOldOld
  uint32 :lcbPgdFtnOldOld
  uint32 :fcBkdFtnOldOld
  uint32 :lcbBkdFtnOldOld
  uint32 :fcPgdEdnOldOld
  uint32 :lcbPgdEdnOldOld
  uint32 :fcBkdEdnOldOld
  uint32 :lcbBkdEdnOldOld
  uint32 :fcSttbfIntlFld
  uint32 :lcbSttbfIntlFld
  uint32 :fcRouteSlip
  uint32 :lcbRouteSlip
  uint32 :fcSttbSavedBy
  uint32 :lcbSttbSavedBy
  uint32 :fcSttbFnm
  uint32 :lcbSttbFnm
  uint32 :fcPlfLst
  uint32 :lcbPlfLst
  uint32 :fcPlfLfo
  uint32 :lcbPlfLfo
  uint32 :fcPlcfTxbxBkd
  uint32 :lcbPlcfTxbxBkd
  uint32 :fcPlcfTxbxHdrBkd
  uint32 :lcbPlcfTxbxHdrBkd
  uint32 :fcDocUndoWord9
  uint32 :lcbDocUndoWord9
  uint32 :fcRgbUse
  uint32 :lcbRgbUse
  uint32 :fcUsp
  uint32 :lcbUsp
  uint32 :fcUskf
  uint32 :lcbUskf
  uint32 :fcPlcupcRgbUse
  uint32 :lcbPlcupcRgbUse
  uint32 :fcPlcupcUsp
  uint32 :lcbPlcupcUsp
  uint32 :fcSttbGlsyStyle
  uint32 :lcbSttbGlsyStyle
  uint32 :fcPlgosl
  uint32 :lcbPlgosl
  uint32 :fcPlcocx
  uint32 :lcbPlcocx
  uint32 :fcPlcfBteLvc
  uint32 :lcbPlcfBteLvc
  uint32 :dwLowDateTime
  uint32 :dwHighDateTime
  uint32 :fcPlcfLvcPre10
  uint32 :lcbPlcfLvcPre10
  uint32 :fcPlcfAsumy
  uint32 :lcbPlcfAsumy
  uint32 :fcPlcfGram
  uint32 :lcbPlcfGram
  uint32 :fcSttbListNames
  uint32 :lcbSttbListNames
  uint32 :fcSttbfUssr
  uint32 :lcbSttbfUssr
end
